name: CI/CD - Nginx Application with Docker
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build-and-deploy:
        name: Build, Push and Deploy Docker Image
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout source code
            - name: Checkout source code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERBANE }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
            # - name: Deploy to Server 1
            #   uses: appleboy/ssh-action@v0.1.7
            #   with:
            #       host: ${{ secrets.SERVER_IP }}
            #       username: ${{ secrets.SERVER_USER }}
            #       key: ${{ secrets.SERVER_SSH_KEY }}
            #       port: ${{ secrets.SERVER_SSH_PORT }}
            #       script: |
            #           docker pull ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
            #           docker stop nginx-app || true
            #           docker rm nginx-app || true
            #           docker run -d --name nginx-app -p 80:80 ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest