name: CI/CD - Nginx Application with Docker
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            # 1 - Checkout source code
            - name: Checkout source code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERBANE }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
    deploy-image:
        name: Deploy Docker Image to Remote Server
        runs-on: ubuntu-latest
        needs: build-image
        steps:
            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
                      docker stop nginx-container || true
                      docker rm nginx-container || true
                      docker run -d -p 80:80 --name nginx-container ${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest